require("core.plugins-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins.treesitter")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.lsp")
require("plugins.harpoon")
require("plugins.nvim-tree")